Timesheets-Django/mysite/authorise/urls.py
from django.urls import path
from . import views
# from django.contrib.auth.views import logout_then_login


app_name = 'authorise'
urlpatterns = [
    path('', views.landing, name='landing'),
    path('logoutUser/', views.logoutUser, name='logout'),
]

Timesheets-Django/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include #,url
from django.contrib.auth import views as auth_views

urlpatterns = [
    #path('polls/', include('polls.urls')) ,
    path('admin/', admin.site.urls),
    #Authorise Users
    path('', include('authorise.urls')),
    path('auth/', include('social_django.urls', namespace='social')),
    path('timekeeping/', include('timekeeping.urls')),
    path('timekeeping/templates/login', auth_views.LoginView.as_view()),
    path('thanks-page/', auth_views.LoginView.as_view()),
    #url(r'^auth/', include('social_django.urls', namespace='social')),  # <- Here
]

Timesheets-Django/mysite/polls/urls.py
# -*- coding: utf-8 -*-
"""
Created on Wed Apr 17 10:39:16 2019

@author: Krishna
"""

from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

Timesheets-Django/mysite/authorise/models.py
from django.db import models

# Create your models here.

Timesheets-Django/mysite/authorise/views.py
from django.shortcuts import render
from django.contrib.auth import logout
from django.shortcuts import HttpResponseRedirect


def landing(request):
    return render(request, 'authorise/landing.html')

def logoutUser(request):
    logout(request)
    return HttpResponseRedirect('/')

Timesheets-Django/mysite/authorise/templates/authorise/landing.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">

  <title>EdgeRed Timesheet</title>

  <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
    integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4"
    crossorigin="anonymous">
</head>
<body>
  <div class="jumbotron">
    <h1>EdgeRed Timesheet</h1>
    {% if user.is_authenticated %}
      <p>Logged as {{ user.username }}</p>
      <a class="btn btn-primary" href="{% url 'authorise:logout' %}">Logout</a>
    {% else %}
      <a class="btn btn-primary" href="{% url 'social:begin' 'google-oauth2' %}">
        Login
      </a>
    {% endif %}
  </div>

  <!-- <div class="container-fluid">
  {% for post in posts %}
    <div>
      <h2>{{ post.title }}</h2>
      <p>{{ post.content }}</p>
      <p>Posted by {{ post.user.username }} | {{ post.date }}</p>
    </div>
  {% endfor %}
  </div> -->
</body>
</html>