Timesheets-Django/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include #,url
from django.contrib.auth import views as auth_views

urlpatterns = [
    #path('polls/', include('polls.urls')) ,
    path('admin/', admin.site.urls),
    #Authorise Users
    path('', include('authorise.urls')),
    path('auth/', include('social_django.urls', namespace='social')),
    path('timekeeping/', include('timekeeping.urls')),
    path('timekeeping/templates/login', auth_views.LoginView.as_view()),
    path('thanks-page/', auth_views.LoginView.as_view()),
    #url(r'^auth/', include('social_django.urls', namespace='social')),  # <- Here
]

Timesheets-Django/mysite/polls/urls.py
# -*- coding: utf-8 -*-
"""
Created on Wed Apr 17 10:39:16 2019

@author: Krishna
"""

from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

Timesheets-Django/mysite/timekeeping/urls.py
from django.urls import path
#from django.contrib.auth import views as auth_views
from . import views

app_name = 'timekeeping'
urlpatterns = [
    #path('', views.index, name='index'),
    path('timesheet', views.timesheet, name='timesheet'),
    path('multibarhorizontalchart/', views.multibarhorizontalchart, name='multibarhorizontalchart'),
    #path('week_display', views.week_display, name='week_display'),
    path('', views.home, name='home'),
    path('thanks-page/', views.sub_func, name='sub_func'),
    path('timekeeping/templates/login', views.Login, name='login'),
    path('test', views.test, name='test'),
    path('<int:dimemployees_id>/detail/', views.detail, name='detail'),
    

]

Timesheets-Django/mysite/timekeeping/models.py
from django.db import models, connections
from django.forms import ModelForm
from django.contrib.postgres.fields import ArrayField

# class Question(models.Model):
#     question_text = models.CharField(max_length=200)
#     pub_date = models.DateTimeField('date published')
    # def __str__(self):
    #   return self.question_text

# class Choice(models.Model):
#     question = models.ForeignKey(Question, on_delete=models.CASCADE)
#     choice_text = models.CharField(max_length=200)
#     votes = models.IntegerField(default=0)

class dimemployees(models.Model):
    name = models.CharField(max_length=50)
    active = models.CharField(max_length=1)
    email = models.EmailField(max_length=100)
    #def __str__(self):
    #    return self.name+"|"+self.active

class dimprojects(models.Model):
    project_id = models.IntegerField()
    client = models.CharField(max_length=200)
    project_name = models.CharField(max_length=200)
    start_date = models.DateField()
    end_date = models.DateField()

class edgered_timesheets(models.Model):
    date = models.DateField()
    hours_worked = models.IntegerField()
    timecode = models.IntegerField()
    name = models.CharField(max_length=50)
    islatest = models.IntegerField()
    date_changed = models.DateTimeField(auto_now=True)



class timesheet_details(models.Model):
    username=models.CharField(max_length=50)
    day_value=models.CharField(max_length=50)
    date_value=models.DateField()
    week_no=models.CharField(max_length=50)
    projects_time=ArrayField(models.CharField(max_length=500))
# import sys,os


# def dictfetchall(cursor):
#     "Return all rows from a cursor as a dict"
#     columns = [col[0] for col in cursor.description]
#     return [
#         dict(zip(columns, row))
#         for row in cursor.fetchall()
#     ]

# from collections import namedtuple

# def namedtuplefetchall(cursor):
#     "Return all rows from a cursor as a namedtuple"
#     desc = cursor.description
#     nt_result = namedtuple('Result', [col[0] for col in desc])
#     return [nt_result(*row) for row in cursor.fetchall()]

# result = namedtuplefetchall(cursor)
# # print(result[1][0])
# i = 0
# while i <= len(result):
#     print(result[i][0])
#     i += 1


# print(Dimemployees)
    # name = result[0]
    # active = result.active
    # email = result.email
    # print(name)
    # print(active)
    # print(email)

# employee = dimemployees.objects.raw('SELECT * FROM timesheets.dimemployees')
# print(employee)

# cnx.close()
# db_conn = connections['default']

Timesheets-Django/mysite/timekeeping/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, render_to_response
from django.contrib.auth.decorators import login_required
from timekeeping.models import dimemployees as de
from timekeeping.models import dimprojects
from timekeeping.models import timesheet_details
from urllib import request
import time
import datetime
from datetime import date
project_name_map={}
#date_day_map={}

"""
from googleapiclient import discovery
from oauth2client import tools
from oauth2client.client import OAuth2WebServerFlow
from oauth2client.file import Storage
import httplib2
"""

def index(request):
    return render(request, 'index.html')
    # name_list = dimemployees.objects.order_by('name')[:5]
    # return render(request, 'timekeeping/index.html', {'name_list': name_list})

"""
def google_calendar_connection():
    flags = tools.argparser.parse_args([])
    FLOW = OAuth2WebServerFlow(
        client_id='xxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com',
        client_secret='xxxxxx',
        scope='https://www.googleapis.com/auth/calendar',
        user_agent='<application name>'
        )
    storage = Storage('calendar.dat')
    credentials = storage.get()
    if credentials is None or credentials.invalid == True:
        credentials = tools.run_flow(FLOW, storage, flags)
    
    # Create an httplib2.Http object to handle our HTTP requests and authorize it
    # with our good Credentials.
    http = httplib2.Http()
    http = credentials.authorize(http)
    service = discovery.build('calendar', 'v3', http=http)
    
    return service
    

def form_valid(self, form):
        service = self.google_calendar_connection()
        
        event = {
          'summary': "new",
          'location': "london",
          'description': "anything",
          'start': {
            'date': "2015-09-02",
          },
          'end': {
            'date': "2015-09-02",
          },
                 
        }
        
        event = service.events().insert(calendarId='primary', body=event).execute()
        
        return CreateView.form_valid(self, form) 

""" 




def home(request):
	return render(request, 'home.html')

def Login(request):
	return render(request, 'login.html')

@login_required
def timesheet(request):
    #return render(request, 'timekeeping/timesheet.html',{"name":[x.name for x in de.objects.all()], "email":de.objects.get(id=1).email})
    print(" ".join(['<option value="Employee {}"> {} </option>'.format(ind+1,x.name) for ind,x in enumerate(de.objects.all())]))
    print(" ".join(['<option value="Project {}"> {} </option>'.format(ind+1,x.project_name) for ind,x in enumerate(dimprojects.objects.all())]))
    wkno=request.POST.get('weekno')
    for ind,x in enumerate(dimprojects.objects.all()):
        key_val="Project {}".format(ind+1)
        project_name_map[key_val]=x.project_name
    global current_user
    current_user=str(request.user)
    email_id=request.user.email
    current_user=current_user.replace(" ", "").rstrip(current_user[-16:])
    cal='<iframe src="https://calendar.google.com/calendar/embed?showPrint=0&amp;mode=WEEK&amp;height=600&amp;wkst=1&amp;bgcolor=%23ffffff&amp;src={}%40edgered.com.au&amp;color=%231B887A&amp;ctz=Australia%2FSydney" style="border:solid 1px #777" width="800" height="600" frameborder="0" scrolling="no"></iframe>'.format(current_user)
    #context['your_html_variable'] = "\n".join(['<option value="Employee {}"> {} </option>'.format(ind+1,x.name) for ind,x in enumerate(de.objects.all())])
    return render(request, 'timesheet.html',{"name":"\n".join(['<option value="Employee {}"> {} </option>'.format(ind+1,x.name) for ind,x in enumerate(de.objects.all())]), "email":de.objects.get(id=1).email,"wkno":wkno,"project_name":" ".join(['<option value="Project {}"> {} </option>'.format(ind+1,x.project_name) for ind,x in enumerate(dimprojects.objects.all())]),"current_user":current_user,"email_id":email_id,"cal":cal})

def email(request, dimemployees_id):
    return HttpResponse("You're looking at %s." % dimemployees_id)

def detail(request, dimemployees_id):
    employee = get_object_or_404(de, pk=dimemployees_id)
    return render(request, 'detail.html', {'employee': employee})

def test(request):
    return HttpResponse(de.objects.all())

def sub_func(request):
    global wkno
    global wkno_bkp
    wkno_bkp=request.GET.get('weekno','')
    wkno=wkno_bkp.split("-")[1].strip("W")
    yr=request.GET.get('weekno','').split("-")[0]
    yr=int(yr)
    #sun_hrs=request.GET.get('sun_hours','')
    sun_hrs= request.GET.getlist('sun_hours')
    sun_pn= request.GET.getlist('sun_pn')
    mon_hrs= request.GET.getlist('mon_hours')
    mon_pn= request.GET.getlist('mon_pn')
    tue_hrs= request.GET.getlist('tue_hours')
    tue_pn= request.GET.getlist('tue_pn')
    wed_hrs= request.GET.getlist('wed_hours')
    wed_pn= request.GET.getlist('wed_pn')
    thu_hrs= request.GET.getlist('thu_hours')
    thu_pn= request.GET.getlist('thu_pn')
    fri_hrs= request.GET.getlist('fri_hours')
    fri_pn= request.GET.getlist('fri_pn')
    sat_hrs= request.GET.getlist('sat_hours')
    sat_pn= request.GET.getlist('sat_pn')
    wkno=int(wkno)
    startdate = time.asctime(time.strptime('%d %d 1' %(yr, wkno), '%Y %W %w'))
    if date(yr, 1, 1).weekday()!=0:
        startdate = datetime.datetime.strptime(startdate, '%a %b %d %H:%M:%S %Y')- datetime.timedelta(days=7)
    else:
        startdate = datetime.datetime.strptime(startdate, '%a %b %d %H:%M:%S %Y')
    dates = [startdate]
    for i in range(1, 7):
        dates.append((startdate + datetime.timedelta(days=i)))
    dates_f=[str(date.date()) for date in dates]
    days=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"]
    global date_day_map
    date_day_map={}
    for day_date in zip(days,dates_f):
        date_day_map[day_date[0]]=day_date[1]
    list_zip=[zip(["Monday" for i in range(0,len(mon_pn))],mon_pn,mon_hrs),zip(["Tuesday" for i in range(0,len(tue_pn))],tue_pn,tue_hrs),zip(["Wednesday" for i in range(0,len(wed_pn))],wed_pn,wed_hrs),zip(["Thursday" for i in range(0,len(thu_pn))],thu_pn,thu_hrs),zip(["Friday" for i in range(0,len(fri_pn))],fri_pn,fri_hrs),zip(["Saturday" for i in range(0,len(sat_pn))],sat_pn,sat_hrs),zip(["Sunday" for i in range(0,len(sun_pn))],sun_pn,sun_hrs)]
    global output_map
    output_map={"Monday":[],"Tuesday":[],"Wednesday":[],"Thursday":[],"Friday":[],"Saturday":[],"Sunday":[]}
    for zip_pn_hr in list_zip:
        for day_pn_hr in zip_pn_hr:
            pn_hr_str='%s|%s'%(project_name_map.get(day_pn_hr[1],''),day_pn_hr[2])
            output_map[day_pn_hr[0]].append(pn_hr_str)

    return render(request, 'week_display.html',{"wkno":wkno,"dates":dates_f, "mon_hrs":mon_hrs,"mon_pn":mon_pn, "tue_hrs":tue_hrs,"tue_pn":tue_pn, "wed_hrs":wed_hrs,"wed_pn":wed_pn, "thu_hrs":thu_hrs,"thu_pn":thu_pn, "fri_hrs":fri_hrs,"fri_pn":fri_pn, "sat_hrs":sat_hrs,"sat_pn":sat_pn,"sun_hrs":sun_hrs,"sun_pn":sun_pn,"project_name_map":project_name_map,"date_day_map":date_day_map,"Monday":date_day_map["Monday"],"Tuesday":date_day_map["Tuesday"],"Wednesday":date_day_map["Wednesday"],"Thursday":date_day_map["Thursday"],"Friday":date_day_map["Friday"],"Saturday":date_day_map["Saturday"],"Sunday":date_day_map["Sunday"],"output_map":output_map,"date_day_map":date_day_map})


def multibarhorizontalchart(request):
    for day in output_map.keys():
        timesheet_details.objects.create(username=current_user,day_value=day,date_value=date_day_map.get(day),week_no=wkno_bkp,projects_time=output_map.get(day))
        #timesheet_details
    xdata = ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"]
    all_projects_names=[x.project_name for x in dimprojects.objects.all()]
    #no_of_series=len(all_projects_names)
    #series_names=all_projects_names
    #proj_time_maps= {k: [] for k in all_projects_names}
    ydata_list=[]
    for pj_nm in all_projects_names:
        day_work_list=[]
        for day in xdata:
            #op_keys=output_map
            ydata_stg = output_map[day]
            for adayswork in ydata_stg:
                hours=0
                if adayswork.split("|")[0]==pj_nm:
                    hours=adayswork.split("|")[1]
                    break;
            day_work_list.append(hours)
        ydata_list.append(day_work_list)   
    extra_serie = {"tooltip": {"y_start": "", "y_end": " hours"}}
    chartdata ={'x': xdata}
    for series_num in range(1,len(all_projects_names)+1):
       nm='name%s'%(series_num)
       y='y%s'%(series_num)
       extra='extra%s'%(series_num)
       chartdata[nm]=all_projects_names[series_num-1]
       chartdata[y]=ydata_list[series_num-1]
       chartdata[extra]=extra_serie
    
    charttype = "multiBarHorizontalChart"
    chartcontainer = 'multibarhorizontalchart_container'  # container name
    data = {
        'charttype': charttype,
        'chartdata': chartdata,
        'chartcontainer': chartcontainer,
        'extra': {
            'x_is_date': False,
            'x_axis_format': '',
            'tag_script_js': True,
            'jquery_on_ready': True,
        },
         "wkno":wkno,
         "date_day_map":date_day_map,
         "output_map":output_map
    }
   # print(abc)
    return render_to_response('multibarhorizontalchart.html', data)
            #ydata_list.append([val.split("|")[1] if val.split("|")[0]==pj_nm else 0 for val in ydata_stg])
            
    #for day in xdata:
        
            
            
            

Timesheets-Django/mysite/timekeeping/templates/detail.html
<h1>{{ employee.name }}</h1>
<ul>
    <li>{{employee.active}}</li>
    <li>{{ employee.email }}</li>
</ul>

Timesheets-Django/mysite/timekeeping/templates/home.html
{% extends "layout.html" %}

{% block content %}
	{% if user.is_authenticated %}
             <p class="display-4">Hello, {{ user.username }}</p>
	{% else %}
            	<p class="display-4">Hello, please login</p>
            	<h2 id="header_1" class="form-header">EDGERED ANALYTICS</h2>
             <a class="lead" href="{% url 'login' %}">Login</a>
	{% endif %}
{% endblock content %}

Timesheets-Django/mysite/timekeeping/templates/index.html
<!DOCTYPE html>
    <html>
        <head>
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <link href="//netdna.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" media="screen">
            <style>
            .container {
            max-width: 1000px;
            }
            </style>
        </head>

        <form action = "" method = "post">
        {% csrf_token %}
        <body>
            <h1>Project</h1>
            {% if user.is_authenticated %}
                <p>Logged as {{ user.username }}</p>
            {% endif %}
            <p>Select a Project</p>

            <select id = "myList" name = "project">
               <option value = "1">one</option>
               <option value = "2">two</option>
               <option value = "3">three</option>
               <option value = "4">four</option>
            </select>


            <h1>Employee</h1>
            <p>Select an Employee</p>

            <select id = "myList" name = "employee">
               <option value = "1">one</option>
               <option value = "2">two</option>
               <option value = "3">three</option>
               <option value = "4">four</option>
            </select>

            <h1>Hours</h1>
            <div class="form-group">
                <input type="text" name="hours" class="form-control" id="url-box" placeholder="Enter Hours" style="max-width: 300px;" autofocus required>
            </div>       
            <div>
                <br>
                <input type="submit" value="Submit">
            </div>
            
            <script src="//code.jquery.com/jquery-2.2.1.min.js"></script>
            <script src="//netdna.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
        </body>
        </form>
    </html>

Timesheets-Django/mysite/timekeeping/templates/index_old.html
{% if name_list %}
    <ul>
    {% for name in name_list %}
        <li>{{ name.name }}</li>
        <!-- <a href="{% url 'timekeeping:index' dimemployee.id}"></a> -->
    {% endfor %}
    </ul>
{% else %}
    <p>No names are available.</p>
{% endif %}

Timesheets-Django/mysite/timekeeping/templates/layout.html
<h2 id="header_1" class="form-header">EDGERED ANALYTICS</h2>

<div id="content">
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
   
</div>

Timesheets-Django/mysite/timekeeping/templates/login.html
{% extends "layout.html" %}


{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
   <br>
 {% endblock %}

Timesheets-Django/mysite/timekeeping/templates/multibarhorizontalchart.html
<html>
{% load nvd3_tags %}
<head>
    {# Jquery CDN : Needed when using jquery_on_ready=True #}
    <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
    {% include_chart_jscss %}
    {% load_chart charttype chartdata chartcontainer extra %}
<style>
body {background-color: #566573;  }
</style>
<img src="https://static.wixstatic.com/media/2fb3e9_ec78e6bc77c14741943cce9dff0f8781~mv2.png/v1/fill/w_250,h_46,al_c,q_80,usm_0.66_1.00_0.01/ER-RED.webp" alt="EdgeRed" style="width:250px;height:50px;display: block;margin-left: auto;margin-right: auto;" >
</head>
<body>
<div style="width:1024px;margin:0 auto;background-color:#F0F3F4">
<h2 style="text-align:center;color:black"> Your work summary for week {{wkno}}</h2>
<style>
.myTable { 
  width: 80%;
  text-align: center;
  background-color: #EDC9AF;
  border-collapse: collapse; 
  margin:1em auto;
  }
.myTable th { 
  background-color: goldenrod;
  color: white; 
  }
.myTable td, 
.myTable th { 
  padding: 10px;
  border: 1px solid goldenrod; 
  }
</style>
<br>
<div>
<table class="myTable">
  <tr >
    <th >Day of week</th>
    <th >Date</th> 
    <th >Project:TimeSpent</th>
  </tr>
  <tr>
    <td >Monday (Week Start)</td>
    <td >{{date_day_map.Monday}}</td>
    <td >{{output_map.Monday}}</td>
  </tr>
  <tr>
    <td >Tuesday</td>
    <td >{{date_day_map.Tuesday}}</td>
    <td >{{output_map.Tuesday}}</td>
  </tr>
  <tr>
    <td >Wednesday</td>
    <td >{{date_day_map.Wednesday}}</td>
    <td >{{output_map.Wednesday}}</td>
  </tr>
    <tr>
    <td >Thursday</td>
    <td >{{date_day_map.Thursday}}</td>
    <td >{{output_map.Thursday}}</td>
  </tr>
    <tr>
    <td>Friday</td>
    <td>{{date_day_map.Friday}}</td>
    <td>{{output_map.Friday}}</td>
  </tr>
    <tr>
    <td >Saturday</td>
    <td >{{date_day_map.Saturday}}</td>
    <td >{{output_map.Saturday}}</td>
  </tr>
    <tr>
    <td>Sunday (Week End)</td>
    <td >{{date_day_map.Sunday}}</td>
    <td >{{output_map.Sunday}}</td>
  </tr>
</table>
</div>
<br>
<br>
<h2 style="text-align:center;color:black"> Graphical view </h2>
    {% include_container chartcontainer 500 1024 %}
<script>
document.getElementById("multibarhorizontalchart_container").style.margin = "0 auto";
document.getElementById("multibarhorizontalchart_container").style.display = "block";

var x = document.getElementsByClassName("nvd3-svg");
var i;
for (i = 0; i < x.length; i++) {
   x[i].style.margin = "0 auto";
}
</script>
</div>
</body>
</html>

Timesheets-Django/mysite/timekeeping/templates/test.html
<!DOCTYPE html>
<html>
    <head>
        <title>Inputs</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="//netdna.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" media="screen">
        <style>
        .container {
        max-width: 1000px;
        }
        </style>
    </head>

    <body>
        <div class="container">
            <h1>Input Your Files</h1>
            <form role="form" method='POST' action='/'>
                <div class="form-group">
                <input type="text" name="Hours" class="form-control" id="url-box" placeholder="Enter Hours" style="max-width: 300px;" autofocus required>
                </div>
                <div class="dropdown">
                    <button class="dropbtn">Dropdown</button>
                    <div class="dropdown-content">
                    <a href="#">Link 1</a>
                    <a href="#">Link 2</a>
                    <a href="#">Link 3</a>
                    </div>
                    <button type="submit" class="btn btn-default">Submit</button>
                </div>
            </form>
        <br>
        {% for error in errors %}
        <h4>{{ error }}</h4>
        {% endfor %}
        </div>
    <script src="//code.jquery.com/jquery-2.2.1.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    </body>
</html>

Timesheets-Django/mysite/timekeeping/templates/timesheet_upd.html
<html class="supernova">
<head>
<style>
table, td {
  border: 1px solid black;
}
</style>
</head>
<form action="/timekeeping" method="post">
<h1>EDGERED ANALYTICS</h1>

Timesheets-Django/mysite/timekeeping/templates/week_display.html
<html>
<head>
<style>
body {background-color: #566573; }
</style>
<img src="https://static.wixstatic.com/media/2fb3e9_ec78e6bc77c14741943cce9dff0f8781~mv2.png/v1/fill/w_250,h_46,al_c,q_80,usm_0.66_1.00_0.01/ER-RED.webp" alt="EdgeRed" style="width:250px;height:50px;display: block;margin-left: auto;margin-right: auto;" >
</head>
<div style="width:1024px;margin:0 auto;background-color:#F0F3F4">
<h2 style="text-align:center;color:black"> Your work summary for week {{wkno}}</h2>
<!-- CSS -->
<style>
.myTable { 
  width: 70%;
  text-align: center;
  background-color: #EDC9AF;
  border-collapse: collapse; 
  margin:1em auto;
  }
.myTable th { 
  background-color: goldenrod;
  color: white; 
  }
.myTable td, 
.myTable th { 
  padding: 10px;
  border: 1px solid goldenrod; 
  }
</style>
<br>
<div>
<table class="myTable">
  <tr >
    <th >Day of week</th>
    <th >Date</th> 
    <th >Project:TimeSpent</th>
  </tr>
  <tr>
    <td >Monday (Week Start)</td>
    <td >{{date_day_map.Monday}}</td>
    <td >{{output_map.Monday}}</td>
  </tr>
  <tr>
    <td >Tuesday</td>
    <td >{{date_day_map.Tuesday}}</td>
    <td >{{output_map.Tuesday}}</td>
  </tr>
  <tr>
    <td >Wednesday</td>
    <td >{{date_day_map.Wednesday}}</td>
    <td >{{output_map.Wednesday}}</td>
  </tr>
    <tr>
    <td >Thursday</td>
    <td >{{date_day_map.Thursday}}</td>
    <td >{{output_map.Thursday}}</td>
  </tr>
    <tr>
    <td>Friday</td>
    <td>{{date_day_map.Friday}}</td>
    <td>{{output_map.Friday}}</td>
  </tr>
    <tr>
    <td >Saturday</td>
    <td >{{date_day_map.Saturday}}</td>
    <td >{{output_map.Saturday}}</td>
  </tr>
    <tr>
    <td>Sunday (Week End)</td>
    <td >{{date_day_map.Sunday}}</td>
    <td >{{output_map.Sunday}}</td>
  </tr>
</table>
</div>
<a href="/timekeeping/multibarhorizontalchart/" style="text-align:center;color:black">Once reviewed, click to save and generate graph</a> <br/>
</div>
</html>

Timesheets-Django/mysite/timekeeping/templates/week_display_old.html
<label>Week number provided is</label>
<label> {{wkno|safe}} </label>
<br>
<label>All dates in this week are:</label>
<label> {{dates|safe}} </label>
<br>
<label>Monday({{Monday}}) hours and projects are:</label>
<label> {{mon_hrs|safe}} </label>
<label> {{mon_pn|safe}} </label>
<br>
<label>Tuesday({{Tuesday}}) hours and projects are:</label>
<label> {{tue_hrs|safe}} </label>
<label> {{tue_pn|safe}} </label>
<br>
<label>Wednesday({{Wednesday|safe}}) hours and projects are:</label>
<label> {{wed_hrs|safe}} </label>
<label> {{wed_pn|safe}} </label>
<br>
<label>Thursday({{Thursday}}) hours and projects are:</label>
<label> {{thu_hrs|safe}} </label>
<label> {{thu_pn|safe}} </label>
<br>
<label>Friday({{Friday}}) hours and projects are:</label>
<label> {{fri_hrs|safe}} </label>
<label> {{fri_pn|safe}} </label>
<br>
<label>Saturday({{Saturday}}) hours and projects are:</label>
<label> {{sat_hrs|safe}} </label>
<label> {{sat_pn|safe}} </label>
<br>
<label>Sunday({{Sunday}}) hours and projects are:</label>
<label> {{sun_hrs|safe}} </label>
<label> {{sun_pn|safe}} </label>
<br>
<label>Project Names mapping is:</label>
<label> {{project_name_map|safe}} </label>
<br>
<label>Output mapping is:</label>
<label> {{output_map|safe}} </label>
<br>
<label>Day and Date mapping is:</label>
<label> {{date_day_map|safe}} </label>
<br>